# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7742ef4e4e392a16c453206fd76296c5fadd2196fc486dae6ce0a89760fe27232414c4896c273caf03e650926d87ed6f0151ae376430de8b3520f948f63473de

test:
  secret_key_base: 2cb93a97365eb780364c9c5795598ce131325dfe4fa75a241e6a07bdeaf15b333d044302542bebc1e85db1a8261dae6308216a043a9c97ecb9e5177f39be1e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
